Repository hyosim-road/hyosim-road-android, pull requests merged in 2025-09, with the labels that each got.

#71 feat: inquiry api #70
  app/src/main/java/com/hyosim/hamkkae/data/datasource/AuthDataSource.kt
  app/src/main/java/com/hyosim/hamkkae/data/datasource/SettingDataSource.kt
  app/src/main/java/com/hyosim/hamkkae/data/datasource_impl/AuthDataSourceImpl.kt
  app/src/main/java/com/hyosim/hamkkae/data/datasource_impl/SettingDataSourceImpl.kt
  app/src/main/java/com/hyosim/hamkkae/data/network/HeaderInterceptor.kt
  app/src/main/java/com/hyosim/hamkkae/data/repository_impl/AuthRepositoryImpl.kt
  app/src/main/java/com/hyosim/hamkkae/data/repository_impl/SettingRepositoryImpl.kt
  app/src/main/java/com/hyosim/hamkkae/data/repository_impl/TokenRepositoryImpl.kt
  app/src/main/java/com/hyosim/hamkkae/data/request_dto/setting/InquiryRequestDto.kt
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/ApiResponse.kt
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/auth/CheckIdResponseData.kt
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/auth/CheckIdResponseDto.kt
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/auth/EmailResponseData.kt
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/auth/EmailResponseDto.kt
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/auth/GetMyIdResponseData.kt
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/auth/GetMyIdResponseDto.kt
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/auth/LoginResponseData.kt
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/auth/LoginResponseDto.kt
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/auth/VerifyIdEmailResponseData.kt
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/auth/VerifyIdEmailResponseDto.kt
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/setting/CheckPasswordResponseData.kt
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/setting/CheckPasswordResponseDto.kt
  app/src/main/java/com/hyosim/hamkkae/data/service/AuthService.kt
  app/src/main/java/com/hyosim/hamkkae/data/service/SettingService.kt
  app/src/main/java/com/hyosim/hamkkae/di/BindModule.kt
  app/src/main/java/com/hyosim/hamkkae/di/RetrofitModule.kt
  app/src/main/java/com/hyosim/hamkkae/domain/model/AskType.kt
  app/src/main/java/com/hyosim/hamkkae/domain/repository/AuthRepository.kt
  app/src/main/java/com/hyosim/hamkkae/domain/repository/SettingRepository.kt
  app/src/main/java/com/hyosim/hamkkae/domain/repository/TokenRepository.kt
  app/src/main/java/com/hyosim/hamkkae/extension/auth/LoginState.kt
  app/src/main/java/com/hyosim/hamkkae/extension/auth/SendTempPwState.kt
  app/src/main/java/com/hyosim/hamkkae/extension/auth/VerifyIdEmailState.kt
  app/src/main/java/com/hyosim/hamkkae/extension/setting/InquiryState.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/auth/find/id/FindIdViewModel.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/auth/login/LoginFragment.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/auth/login/LoginViewModel.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/auth/signup/SignupInfoViewModel.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/setting/support/CustomerCenterFragment.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/setting/support/CustomerCenterViewModel.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/setting/user/ChangePwViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ✨ feat

#83 feat: register course api #75
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hyosim/hamkkae/data/datasource/PlanDataSource.kt
  app/src/main/java/com/hyosim/hamkkae/data/datasource_impl/PlanDataSourceImpl.kt
  app/src/main/java/com/hyosim/hamkkae/data/repository_impl/PlanRepositoryImpl.kt
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/plan/CourseRecommendResponseData.kt
  app/src/main/java/com/hyosim/hamkkae/data/service/PlanService.kt
  app/src/main/java/com/hyosim/hamkkae/domain/repository/PlanRepository.kt
  app/src/main/java/com/hyosim/hamkkae/extension/plan/RegisterState.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/plan/PlanViewModel.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/plan/recommend/RecommendCourseFragment.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/plan/recommend/RecommendCourseViewModel.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/plan/recommend/detail/RecommendDetailFragment.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/plan/trip_start/TripStartAdapter.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/plan/trip_start/TripStartFragment.kt
  app/src/main/res/navigation/plan_nav_graph.xml
Labels: 🔨 refactor

#84 feat: check in progress api #76
  app/src/main/java/com/hyosim/hamkkae/data/datasource/HomeDataSource.kt
  app/src/main/java/com/hyosim/hamkkae/data/datasource_impl/HomeDataSourceImpl.kt
  app/src/main/java/com/hyosim/hamkkae/data/repository_impl/HomeRepositoryImpl.kt
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/home/ProgressTripResponseDto.kt
  app/src/main/java/com/hyosim/hamkkae/data/service/HomeService.kt
  app/src/main/java/com/hyosim/hamkkae/di/BindModule.kt
  app/src/main/java/com/hyosim/hamkkae/di/service/HomeModule.kt
  app/src/main/java/com/hyosim/hamkkae/domain/repository/HomeRepository.kt
  app/src/main/java/com/hyosim/hamkkae/extension/home/ProgressTripState.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/home/MainActivity.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/home/MainViewModel.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/home/adapter/today_schedule/TodayScheduleAdapter.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/plan/recommend/RecommendCourseViewModel.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/setting/SettingFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat, 🔨 refactor

#86 refactor: course-detail #85
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/home/ProgressTripResponseDto.kt
  app/src/main/java/com/hyosim/hamkkae/extension/home/AttractionResult.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/home/MainActivity.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/home/MainViewModel.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/home/adapter/RecentAdapter.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/home/adapter/TodayScheduleAdapter.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/home/adapter/TripRecordAdapter.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/home/adapter/recent/RecentDiffCallback.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/home/adapter/today_schedule/TodayScheduleDiffCallback.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/home/adapter/trip_record/TripRecordDiffCallback.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/plan/trip_start/TripStartAdapter.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/plan/trip_start/TripStartFragment.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/trip_continue/TripDetailActivity.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/trip_continue/TripDetailAlbumFragment.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/trip_continue/schedule/TripDetailScheduleAdapter.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/trip_detail/TripDetailActivity.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/trip_detail/TripDetailViewModel.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/trip_detail/album/TextAdapter.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/trip_detail/album/TripDetailAlbumFragment.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/trip_detail/album/TripDetailAlbumViewModel.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/trip_detail/schedule/TripDetailScheduleAdapter.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/trip_detail/schedule/TripDetailScheduleFragment.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/trip_detail/schedule/TripDetailScheduleViewModel.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/trip_records/detail/visited/VisitedAdapter.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/upload_photo/UploadPhotoActivity.kt
  app/src/main/res/layout/activity_trip_detail.xml
  app/src/main/res/layout/fragment_trip_detail_schedule.xml
  app/src/main/res/layout/item_trip_schedule.xml
Labels: 🔨 refactor

#91 feat: filter in map #44
  app/src/main/java/com/hyosim/hamkkae/presentation/main/map/MapActivity.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/map/MapFragment.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/map/MapLabelClickListener.kt
  app/src/main/res/drawable/bg_filter_attraction_default.xml
  app/src/main/res/drawable/bg_filter_attraction_selected.xml
  app/src/main/res/drawable/bg_filter_attraction_selector.xml
  app/src/main/res/drawable/bg_filter_lodging_default.xml
  app/src/main/res/drawable/bg_filter_lodging_selected.xml
  app/src/main/res/drawable/bg_filter_lodging_selector.xml
  app/src/main/res/drawable/bg_filter_restaurant_default.xml
  app/src/main/res/drawable/bg_filter_restaurant_selected.xml
  app/src/main/res/drawable/bg_filter_restaurant_selector.xml
  app/src/main/res/drawable/ic_lodging_white.png
  app/src/main/res/drawable/ic_restaurant_white.png
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/values/colors.xml
Labels: ✨ feat

#94 refactor: setting
  app/src/main/java/com/hyosim/hamkkae/presentation/main/setting/SettingFragment.kt
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/fragment_signup_personal.xml
  app/src/main/res/layout/fragment_signup_service.xml
  app/src/main/res/navigation/setting_nav_graph.xml
Labels: 🔨 refactor

#99 refactor: recommend api
  app/src/main/.DS_Store
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/plan/AiCourseRecommendResponseDto.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/home/MainActivity.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/plan/PlanViewModel.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/plan/recommend/RecommendCourseFragment.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/plan/recommend/RecommendCourseViewModel.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/plan/recommend/RecommendLoadingFragment.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/plan/recommend/adapter/RecommendCourseAdapter.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/plan/recommend/detail/RecommendDetailFragment.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/plan/select/SelectTripStyleFragment.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/plan/select/SelectTripStyleViewModel.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/plan/select/adapter/SelectTripStyleAdapter.kt
  app/src/main/res/drawable/ic_default.png
  app/src/main/res/drawable/ic_error_black_24.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_recommend_detail.xml
  app/src/main/res/layout/fragment_recommend_loading.xml
  app/src/main/res/layout/item_recommend_course.xml
  app/src/main/res/values/strings.xml
Labels: 🔨 refactor

#101 feat: conversation api
  app/src/main/java/com/hyosim/hamkkae/data/datasource/ConversationDataSource.kt
  app/src/main/java/com/hyosim/hamkkae/data/datasource_impl/ConversationDataSourceImpl.kt
  app/src/main/java/com/hyosim/hamkkae/data/repository_impl/ConversationRepositoryImpl.kt
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/conversation/GetAnswersResponseData.kt
  app/src/main/java/com/hyosim/hamkkae/data/response_dto/conversation/PostAnswerResponseData.kt
  app/src/main/java/com/hyosim/hamkkae/data/service/ConversationService.kt
  app/src/main/java/com/hyosim/hamkkae/domain/repository/ConversationRepository.kt
  app/src/main/java/com/hyosim/hamkkae/extension/conversation/GetAnswersState.kt
  app/src/main/java/com/hyosim/hamkkae/extension/conversation/PostAnswerState.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/family_conversation/FamilyConversationActivity.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/family_conversation/FamilyConversationViewModel.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/family_conversation/adapter/ConversationAdapter.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/family_conversation/adapter/KeywordAdapter.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/home/MainActivity.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/home/noWordBreak.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/trip_detail/TripDetailActivity.kt
  app/src/main/res/layout/activity_family_conversation.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/activity_trip_detail.xml
  app/src/main/res/layout/fragment_signup_service.xml
  app/src/main/res/layout/item_answer.xml
  app/src/main/res/layout/item_conversation_answer.xml
  app/src/main/res/layout/item_recommend_detail_detail.xml
  app/src/main/res/layout/item_recommend_detail_info.xml
  app/src/main/res/layout/item_trip_records_detail.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat

#102 refactor: show answerlist in detail
  app/src/main/java/com/hyosim/hamkkae/data/datasource/ConversationDataSource.kt
  app/src/main/java/com/hyosim/hamkkae/data/datasource_impl/ConversationDataSourceImpl.kt
  app/src/main/java/com/hyosim/hamkkae/data/repository_impl/ConversationRepositoryImpl.kt
  app/src/main/java/com/hyosim/hamkkae/data/service/ConversationService.kt
  app/src/main/java/com/hyosim/hamkkae/domain/repository/ConversationRepository.kt
  app/src/main/java/com/hyosim/hamkkae/extension/conversation/CountState.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/home/MainActivity.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/home/MainViewModel.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/trip_detail/TripDetailActivity.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/trip_detail/schedule/TripDetailScheduleFragment.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/trip_detail/schedule/TripDetailScheduleViewModel.kt
  app/src/main/res/layout/activity_trip_detail.xml
  app/src/main/res/layout/fragment_trip_detail_schedule.xml
Labels: ✨ feat, 🔨 refactor

#103 refactor: remove alert
  .DS_Store
  app/.DS_Store
  app/release/baselineProfiles/0/app-release.dm
  app/release/baselineProfiles/1/app-release.dm
  app/release/output-metadata.json
  app/src/main/java/com/hyosim/hamkkae/presentation/auth/signup/SignupInfoFragment.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/auth/signup/SignupInfoViewModel.kt
  app/src/main/java/com/hyosim/hamkkae/presentation/main/setting/SettingFragment.kt
  app/src/main/res/layout/fragment_recommend_detail.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/item_recommend_course.xml
Labels: 🔨 refactor
